name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    
    - name: Run staticcheck
      run: staticcheck ./...

  build-cross-platform:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o build/coupongo-linux-amd64 ./cmd/cli
        GOOS=linux GOARCH=arm64 go build -o build/coupongo-linux-arm64 ./cmd/cli
        GOOS=darwin GOARCH=amd64 go build -o build/coupongo-darwin-amd64 ./cmd/cli
        GOOS=darwin GOARCH=arm64 go build -o build/coupongo-darwin-arm64 ./cmd/cli
        GOOS=windows GOARCH=amd64 go build -o build/coupongo-windows-amd64.exe ./cmd/cli
        GOOS=windows GOARCH=arm64 go build -o build/coupongo-windows-arm64.exe ./cmd/cli

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: build/